apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        # don't change this. default istio controller port is 80
        number: 80
        name: grpc
        protocol: TCP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
    - productpage
  gateways:
    - bookinfo-gateway
  tcp:
    - route:
      - destination:
          host: productpage
          port:
            number: 3000
