##################################################################################################
# Reviews service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: reviews
  # label for this service
  labels:
    app: reviews
    service: reviews
spec:
  ports:
    - port: 3001 # port exposed by this service for use within the cluster
      name: grpc
      targetPort: 3001 # targetPort is container port where this service will forward the request to
      protocol: TCP
  selector:
    app: reviews # pods with following labels will be serviced by this Service. Pods are created below as part of deployment.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-reviews
  labels:
    account: reviews
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v1
  # labels for this deployment
  labels:
    app: reviews
    version: v1
spec:
  replicas: 1
  selector:
    # pod with following labels will be selected as part of this deployment. The label is assigned to pods below in template
    matchLabels:
      app: reviews
      version: v1
  template:
    metadata:
      labels:
        # following labels are assigned to the pods created under this deployment
        app: reviews
        version: v1
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
        - name: reviews
          image: docker.io/devnryn/reviews:v1
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v2
  # label for this deployment
  labels:
    app: reviews
    version: v2
spec:
  replicas: 1
  selector:
    # pods with following labels will fall under this deployment
    matchLabels:
      app: reviews
      version: v2
  template:
    metadata:
      # following labels are being assigned to the pods
      labels:
        app: reviews
        version: v2
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
        - name: reviews
          image: docker.io/devnryn/reviews:v2
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v3
  labels:
    app: reviews
    version: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v3
  template:
    metadata:
      labels:
        app: reviews
        version: v3
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
        - name: reviews
          image: docker.io/devnryn/reviews:v3
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 3001
---